#!/usr/bin/env python3
"""
QAOA Circuit Test - Single GPU
Test the specific 32-qubit QAOA circuit from read_circuit.md on AMD GPU

This script loads a pre-defined QAOA circuit in QASM3 format and runs
it on a single GPU using Qiskit Aer with ROCm acceleration.

Features:
    - 32-qubit QAOA circuit with 4 parametrizable values
    - Single GPU execution with ROCm
    - Circuit optimization and transpilation
    - Performance timing and analysis
    - Memory usage reporting

Requirements:
    - qiskit-aer-gpu-rocm installed
    - AMD GPU with ROCm support

Usage:
    # Default: complex128, 100 shots
    python3 qaoa_test.py
    
    # Custom precision
    python3 qaoa_test.py --precision complex64
    
    # Custom shots
    python3 qaoa_test.py --shots 1024
    
    # Custom parameters
    python3 qaoa_test.py --params 0.5,0.3,0.6,0.4
"""

import argparse
import subprocess
import sys
import time
from qiskit_aer import AerSimulator
from qiskit import qasm3, transpile
import numpy as np


# QASM3 circuit definition from read_circuit.md
QASM_CIRCUIT = """
// Generated by Classiq.
// Classiq version: 0.105.0
// Creation timestamp: 2026-02-02T23:14:51.541222+00:00
// Random seed: 4031419110

OPENQASM 3.0;
include "stdgates.inc";
input float[64] params_param_0;
input float[64] params_param_1;
input float[64] params_param_2;
input float[64] params_param_3;
qubit[32] q;
h q[0];
h q[1];
h q[2];
h q[3];
h q[4];
h q[5];
h q[6];
cx q[5], q[6];
rz(-0.125*params_param_0) q[6];
cx q[5], q[6];
cx q[4], q[5];
rz(-0.125*params_param_0) q[5];
cx q[4], q[5];
h q[7];
h q[8];
h q[9];
cx q[8], q[9];
rz(-0.125*params_param_0) q[9];
cx q[8], q[9];
cx q[7], q[8];
rz(-0.125*params_param_0) q[8];
cx q[7], q[8];
rz(0.525*params_param_0) q[8];
h q[10];
h q[11];
rz(-0.125*params_param_0) q[11];
h q[12];
cx q[12], q[3];
rz(0.25*params_param_0) q[3];
cx q[12], q[3];
cx q[0], q[12];
rz(0.25*params_param_0) q[12];
cx q[0], q[12];
cx q[0], q[1];
rz(-0.125*params_param_0) q[1];
cx q[0], q[1];
rz(0.775*params_param_0) q[0];
h q[13];
h q[14];
cx q[14], q[5];
rz(0.25*params_param_0) q[5];
cx q[14], q[5];
h q[15];
cx q[15], q[7];
rz(0.25*params_param_0) q[7];
cx q[15], q[7];
cx q[7], q[9];
rz(-0.125*params_param_0) q[9];
cx q[7], q[9];
cx q[5], q[9];
rz(-0.125*params_param_0) q[9];
cx q[5], q[9];
cx q[15], q[9];
rz(0.25*params_param_0) q[9];
cx q[15], q[9];
cx q[11], q[9];
rz(0.25*params_param_0) q[9];
cx q[11], q[9];
h q[16];
h q[17];
cx q[17], q[2];
rz(-0.5*params_param_0) q[2];
cx q[17], q[2];
cx q[13], q[2];
rz(0.25*params_param_0) q[2];
cx q[13], q[2];
cx q[8], q[2];
rz(-0.125*params_param_0) q[2];
cx q[8], q[2];
cx q[6], q[2];
rz(-0.125*params_param_0) q[2];
cx q[6], q[2];
cx q[4], q[2];
rz(-0.125*params_param_0) q[2];
cx q[4], q[2];
cx q[3], q[2];
rz(-0.125*params_param_0) q[2];
cx q[3], q[2];
rz(1.275*params_param_0) q[2];
cx q[3], q[5];
cx q[4], q[8];
rz(-0.125*params_param_0) q[5];
cx q[3], q[5];
cx q[3], q[9];
rz(-0.125*params_param_0) q[8];
cx q[4], q[8];
rz(0.525*params_param_0) q[4];
rz(-0.125*params_param_0) q[9];
cx q[3], q[9];
rz(0.275*params_param_0) q[9];
rx(params_param_1) q[9];
cx q[11], q[5];
rz(0.25*params_param_0) q[5];
cx q[11], q[5];
rz(0.275*params_param_0) q[5];
rx(params_param_1) q[5];
cx q[13], q[6];
rz(0.25*params_param_0) q[6];
cx q[13], q[6];
cx q[14], q[6];
rz(0.25*params_param_0) q[6];
cx q[14], q[6];
rz(0.55*params_param_0) q[6];
cx q[4], q[6];
rz(-0.125*params_param_0) q[6];
cx q[4], q[6];
cx q[3], q[4];
rz(-0.125*params_param_0) q[4];
cx q[3], q[4];
rz(0.525*params_param_0) q[3];
rz(-0.125*params_param_0) q[14];
h q[18];
cx q[1], q[18];
rz(-0.5*params_param_0) q[18];
cx q[1], q[18];
h q[19];
h q[20];
cx q[19], q[20];
rz(-0.125*params_param_0) q[20];
cx q[19], q[20];
cx q[16], q[19];
rz(-0.125*params_param_0) q[19];
cx q[16], q[19];
rz(0.775*params_param_0) q[19];
h q[21];
h q[22];
cx q[21], q[22];
rz(-0.125*params_param_0) q[22];
cx q[21], q[22];
cx q[19], q[21];
cx q[20], q[22];
rz(-0.125*params_param_0) q[21];
cx q[19], q[21];
rz(-0.125*params_param_0) q[22];
cx q[20], q[22];
h q[23];
h q[24];
cx q[18], q[24];
rz(-0.125*params_param_0) q[24];
cx q[18], q[24];
h q[25];
cx q[24], q[25];
rz(-0.125*params_param_0) q[25];
cx q[24], q[25];
h q[26];
cx q[10], q[26];
rz(-0.125*params_param_0) q[26];
cx q[10], q[26];
cx q[10], q[7];
rz(0.25*params_param_0) q[7];
cx q[10], q[7];
cx q[1], q[7];
rz(-0.125*params_param_0) q[7];
cx q[1], q[7];
cx q[0], q[7];
cx q[1], q[13];
rz(-0.125*params_param_0) q[7];
cx q[0], q[7];
rz(0.525*params_param_0) q[7];
rx(params_param_1) q[7];
rz(-0.75*params_param_0) q[10];
rz(0.25*params_param_0) q[13];
cx q[1], q[13];
rz(-0.875*params_param_0) q[13];
rx(params_param_1) q[13];
h q[27];
cx q[25], q[27];
rz(0.25*params_param_0) q[27];
cx q[25], q[27];
h q[28];
cx q[28], q[16];
rz(0.25*params_param_0) q[16];
cx q[28], q[16];
cx q[16], q[17];
rz(-0.125*params_param_0) q[17];
cx q[16], q[17];
cx q[28], q[19];
rz(0.25*params_param_0) q[19];
cx q[28], q[19];
cx q[17], q[19];
rz(-0.125*params_param_0) q[19];
cx q[17], q[19];
cx q[19], q[22];
rz(-0.125*params_param_0) q[22];
cx q[19], q[22];
rz(0.275*params_param_0) q[19];
rx(params_param_1) q[19];
rz(0.525*params_param_0) q[22];
rx(params_param_1) q[22];
cx q[17], q[21];
rz(-0.125*params_param_0) q[21];
cx q[17], q[21];
cx q[21], q[20];
rz(-0.125*params_param_0) q[20];
cx q[21], q[20];
rz(0.775*params_param_0) q[20];
rx(params_param_1) q[20];
rz(0.775*params_param_0) q[21];
rx(params_param_1) q[21];
cx q[28], q[17];
rz(-0.125*params_param_0) q[17];
cx q[28], q[17];
rz(-0.625*params_param_0) q[17];
rx(params_param_1) q[17];
h q[29];
cx q[29], q[1];
rz(0.25*params_param_0) q[1];
cx q[29], q[1];
cx q[16], q[1];
rz(-0.125*params_param_0) q[1];
cx q[16], q[1];
rz(-0.375*params_param_0) q[1];
rx(params_param_1) q[1];
rz(0.275*params_param_0) q[16];
rx(params_param_1) q[16];
cx q[27], q[28];
rz(-0.125*params_param_0) q[28];
cx q[27], q[28];
rz(-0.125*params_param_0) q[27];
rx(params_param_1) q[27];
rz(0.525*params_param_0) q[28];
rx(params_param_1) q[28];
h q[30];
cx q[30], q[23];
rz(0.25*params_param_0) q[23];
cx q[30], q[23];
cx q[23], q[26];
rz(-0.125*params_param_0) q[26];
cx q[23], q[26];
rz(-0.625*params_param_0) q[23];
rx(params_param_1) q[23];
rz(0.525*params_param_0) q[26];
rx(params_param_1) q[26];
cx q[25], q[26];
rz(0.25*params_param_0) q[26];
cx q[25], q[26];
cx q[25], q[24];
rz(-0.125*params_param_0) q[24];
cx q[25], q[24];
cx q[18], q[24];
rz(-0.125*params_param_0) q[24];
cx q[18], q[24];
rz(-0.125*params_param_0) q[18];
rx(params_param_1) q[18];
rz(0.775*params_param_0) q[24];
rx(params_param_1) q[24];
cx q[10], q[25];
rz(0.25*params_param_0) q[25];
cx q[10], q[25];
rz(0.525*params_param_0) q[25];
rx(params_param_1) q[25];
h q[31];
cx q[10], q[31];
rz(0.25*params_param_0) q[31];
cx q[10], q[31];
cx q[0], q[10];
rz(-0.125*params_param_0) q[10];
cx q[0], q[10];
cx q[0], q[12];
rz(-0.125*params_param_0) q[12];
cx q[0], q[12];
cx q[29], q[12];
rz(0.25*params_param_0) q[12];
cx q[29], q[12];
cx q[12], q[14];
rz(-0.125*params_param_0) q[14];
cx q[12], q[14];
cx q[11], q[14];
rz(0.25*params_param_0) q[14];
cx q[11], q[14];
cx q[15], q[14];
rz(0.25*params_param_0) q[14];
cx q[15], q[14];
rz(0.525*params_param_0) q[14];
rx(params_param_1) q[14];
cx q[12], q[15];
rz(-0.125*params_param_0) q[15];
cx q[12], q[15];
rz(-0.125*params_param_0) q[12];
rx(params_param_1) q[12];
rz(0.525*params_param_0) q[15];
rx(params_param_1) q[15];
cx q[11], q[10];
rz(0.25*params_param_0) q[10];
cx q[11], q[10];
cx q[10], q[6];
rz(-0.125*params_param_0) q[6];
cx q[10], q[6];
rz(-0.125*params_param_0) q[6];
rx(params_param_1) q[6];
rz(0.525*params_param_0) q[10];
rx(params_param_1) q[10];
cx q[30], q[11];
rz(0.25*params_param_0) q[11];
cx q[30], q[11];
cx q[11], q[8];
rz(-0.125*params_param_0) q[8];
cx q[11], q[8];
cx q[8], q[4];
rz(-0.125*params_param_0) q[4];
cx q[8], q[4];
cx q[8], q[3];
rz(-0.125*params_param_0) q[3];
cx q[8], q[3];
rz(0.525*params_param_0) q[3];
rx(params_param_1) q[3];
rz(0.525*params_param_0) q[4];
rx(params_param_1) q[4];
rz(0.525*params_param_0) q[8];
rx(params_param_1) q[8];
cx q[11], q[13];
rz(-0.125*params_param_0) q[13];
cx q[11], q[13];
rz(-0.625*params_param_0) q[11];
rx(params_param_1) q[11];
cx q[13], q[2];
rz(-0.125*params_param_0) q[2];
cx q[13], q[2];
rz(-0.125*params_param_0) q[2];
rx(params_param_1) q[2];
rz(0.525*params_param_0) q[13];
rx(params_param_1) q[13];
cx q[29], q[0];
rz(-0.125*params_param_0) q[0];
cx q[29], q[0];
rz(-0.375*params_param_0) q[0];
rx(params_param_1) q[0];
rz(-0.625*params_param_0) q[29];
rx(params_param_1) q[29];
rz(-0.875*params_param_0) q[30];
rx(params_param_1) q[30];
cx q[31], q[27];
rz(0.25*params_param_0) q[27];
cx q[31], q[27];
rz(-0.125*params_param_0) q[27];
rx(params_param_1) q[27];
rz(-0.125*params_param_0) q[31];
rx(params_param_1) q[31];
rx(params_param_2) q[2];
rx(params_param_2) q[3];
rx(params_param_2) q[4];
cx q[5], q[2];
rz(0.25*params_param_2) q[2];
cx q[5], q[2];
rx(params_param_2) q[5];
cx q[6], q[2];
rz(0.25*params_param_2) q[2];
cx q[6], q[2];
rx(params_param_2) q[6];
cx q[7], q[2];
rz(0.25*params_param_2) q[2];
cx q[7], q[2];
rx(params_param_2) q[7];
rx(params_param_2) q[8];
cx q[9], q[2];
rz(0.25*params_param_2) q[2];
cx q[9], q[2];
rx(params_param_2) q[9];
cx q[13], q[2];
rz(0.25*params_param_2) q[2];
cx q[13], q[2];
cx q[8], q[2];
rz(-0.125*params_param_2) q[2];
cx q[8], q[2];
cx q[4], q[2];
rz(-0.125*params_param_2) q[2];
cx q[4], q[2];
cx q[3], q[2];
rz(-0.125*params_param_2) q[2];
cx q[3], q[2];
rx(params_param_2) q[2];
rx(params_param_2) q[13];
rx(params_param_2) q[10];
cx q[11], q[8];
rz(0.25*params_param_2) q[8];
cx q[11], q[8];
cx q[0], q[8];
rz(-0.125*params_param_2) q[8];
cx q[0], q[8];
rx(params_param_3) q[8];
cx q[11], q[3];
rz(0.25*params_param_2) q[3];
cx q[11], q[3];
rx(params_param_3) q[11];
cx q[12], q[4];
rz(0.25*params_param_2) q[4];
cx q[12], q[4];
rx(params_param_3) q[12];
cx q[14], q[4];
rz(0.25*params_param_2) q[4];
cx q[14], q[4];
cx q[0], q[4];
rz(-0.125*params_param_2) q[4];
cx q[0], q[4];
cx q[0], q[3];
rz(-0.125*params_param_2) q[3];
cx q[0], q[3];
rx(params_param_3) q[0];
rx(params_param_3) q[3];
rx(params_param_3) q[4];
rx(params_param_3) q[14];
rz(-0.125*params_param_2) q[15];
rx(params_param_3) q[15];
cx q[24], q[31];
rz(0.25*params_param_2) q[31];
cx q[24], q[31];
cx q[24], q[28];
rz(0.25*params_param_2) q[28];
cx q[24], q[28];
cx q[23], q[24];
rz(-0.125*params_param_2) q[24];
cx q[23], q[24];
rz(0.275*params_param_2) q[23];
rz(0.525*params_param_2) q[24];
cx q[28], q[20];
rz(0.25*params_param_2) q[20];
cx q[28], q[20];
rz(0.525*params_param_2) q[20];
rz(-0.625*params_param_2) q[28];
rx(params_param_3) q[28];
cx q[30], q[20];
rz(0.25*params_param_2) q[20];
cx q[30], q[20];
cx q[24], q[20];
rz(-0.125*params_param_2) q[20];
cx q[24], q[20];
cx q[18], q[20];
rz(-0.125*params_param_2) q[20];
cx q[18], q[20];
rx(params_param_3) q[18];
rx(params_param_3) q[20];
rx(params_param_3) q[24];
rx(params_param_3) q[30];
rz(-0.125*params_param_2) q[31];
cx q[25], q[31];
rz(0.25*params_param_2) q[31];
cx q[25], q[31];
cx q[23], q[25];
rz(-0.125*params_param_2) q[25];
cx q[23], q[25];
rx(params_param_3) q[23];
rx(params_param_3) q[25];
rx(params_param_3) q[31];
"""


def get_gpu_info():
    """Get GPU model and memory information"""
    gpu_model = "Unknown"
    gpu_memory = None
    
    try:
        # Get GPU model
        result = subprocess.run(
            ['rocm-smi', '--showproductname'],
            capture_output=True, text=True, timeout=10
        )
        if result.returncode == 0:
            for line in result.stdout.split('\n'):
                if 'GPU[0]' in line:
                    gpu_model = line.split(':')[-1].strip()
        
        # Get GPU memory
        result = subprocess.run(
            ['rocm-smi', '--showmeminfo', 'vram'],
            capture_output=True, text=True, timeout=10
        )
        if result.returncode == 0:
            for line in result.stdout.split('\n'):
                if 'VRAM Total Memory' in line and 'GPU[0]' in line:
                    parts = line.split(':')
                    if len(parts) >= 3:
                        try:
                            memory_bytes = float(parts[-1].strip())
                            gpu_memory = memory_bytes / (1024 ** 3)
                        except ValueError:
                            pass
    except Exception as e:
        print(f"Warning: Could not detect GPU info: {e}")
    
    return gpu_model, gpu_memory


def load_qaoa_circuit(param_values):
    """
    Load the QAOA circuit from QASM3 with specified parameters.
    
    Args:
        param_values: List of 4 float values for the circuit parameters
    
    Returns:
        QuantumCircuit: The loaded circuit
    """
    try:
        # Load circuit from QASM3
        circuit = qasm3.loads(QASM_CIRCUIT)
        
        # Bind parameters
        # The circuit expects: params_param_0, params_param_1, params_param_2, params_param_3
        param_dict = {
            'params_param_0': param_values[0],
            'params_param_1': param_values[1],
            'params_param_2': param_values[2],
            'params_param_3': param_values[3]
        }
        
        # Assign parameters
        circuit = circuit.assign_parameters(param_dict)
        
        # Add measurements
        circuit.measure_all()
        
        return circuit
    except Exception as e:
        print(f"Error loading circuit: {e}")
        raise


def show_system_info(precision='complex128'):
    """Display system information and GPU capabilities"""
    print("="*70)
    print("QAOA CIRCUIT TEST - SINGLE GPU")
    print("="*70)
    print()
    
    # Precision info
    bytes_per_element = 16 if precision == 'complex128' else 8
    print(f"Precision: {precision} ({bytes_per_element} bytes per complex number)")
    if precision == 'complex64':
        print("  ⚠️  Note: complex64 uses half memory but reduced accuracy")
    print()
    
    # Check GPU
    sim = AerSimulator()
    devices = sim.available_devices()
    
    if 'GPU' not in devices:
        print("✗ No GPU detected. Make sure ROCm is properly installed.")
        return False
    
    try:
        gpu_sim = AerSimulator(device='GPU')
        print("✓ GPU acceleration available")
        
        # GPU info
        gpu_model, gpu_memory = get_gpu_info()
        print(f"✓ GPU Model: {gpu_model}")
        if gpu_memory:
            print(f"✓ GPU Memory: {gpu_memory:.1f} GB")
        
        return True
    except Exception as e:
        print(f"✗ GPU initialization failed: {e}")
        return False


def run_qaoa_test(param_values, shots=100, precision='complex128'):
    """
    Run the QAOA circuit test on GPU.
    
    Args:
        param_values: List of 4 parameter values
        shots: Number of measurement shots
        precision: 'complex128' or 'complex64'
    
    Returns:
        dict: Results including timing and circuit info
    """
    print("\n" + "="*70)
    print("LOADING AND PREPARING CIRCUIT")
    print("="*70)
    
    # Load circuit
    print("Loading QAOA circuit from QASM3...")
    circuit = load_qaoa_circuit(param_values)
    
    print(f"✓ Circuit loaded: {circuit.num_qubits} qubits")
    print(f"  Parameters: {param_values}")
    
    # Circuit specs before optimization
    print(f"  Depth (before optimization): {circuit.depth()}")
    print(f"  Gates (before optimization): {sum(circuit.count_ops().values())}")
    
    # Calculate memory requirements
    bytes_per_element = 16 if precision == 'complex128' else 8
    state_vector_gb = (2 ** circuit.num_qubits) * bytes_per_element / (1024 ** 3)
    print(f"  State vector size: {state_vector_gb:.2f} GB")
    print()
    
    # Setup GPU simulator
    print("Setting up GPU simulator...")
    aer_precision = 'double' if precision == 'complex128' else 'single'
    backend = AerSimulator(method='statevector', device='GPU', precision=aer_precision)
    print("✓ GPU simulator initialized")
    print()
    
    # Transpile circuit for Aer GPU
    print("Transpiling circuit for GPU...")
    start_transpile = time.time()
    circuit_transpiled = transpile(circuit, backend, optimization_level=3)
    transpile_time = time.time() - start_transpile
    
    print(f"✓ Circuit transpiled in {transpile_time:.3f}s")
    print(f"  Depth (after optimization): {circuit_transpiled.depth()}")
    print(f"  Gates (after optimization): {sum(circuit_transpiled.count_ops().values())}")
    gate_counts = circuit_transpiled.count_ops()
    print(f"  Gate breakdown: {dict(gate_counts)}")
    print()
    
    # Execute on GPU
    print("="*70)
    print("EXECUTING ON GPU")
    print("="*70)
    print(f"Running {shots} shots on GPU...")
    
    # Configure blocking for 32-qubit circuit
    run_options = {
        'shots': shots,
        'seed_simulator': 42,
        'blocking_enable': True,
        'blocking_qubits': 27
    }
    
    try:
        start_exec = time.time()
        result = backend.run(circuit_transpiled, **run_options).result()
        exec_time = time.time() - start_exec
        
        print(f"✓ Execution completed in {exec_time:.4f}s")
        print(f"  Throughput: {shots / exec_time:.2f} shots/sec")
        
        # Get measurement results
        counts = result.get_counts()
        print(f"  Unique outcomes: {len(counts)}")
        
        # Show top 5 most probable outcomes
        sorted_counts = sorted(counts.items(), key=lambda x: x[1], reverse=True)[:5]
        print(f"  Top 5 outcomes:")
        for bitstring, count in sorted_counts:
            prob = count / shots * 100
            print(f"    {bitstring}: {count} ({prob:.2f}%)")
        
        return {
            'success': True,
            'exec_time': exec_time,
            'transpile_time': transpile_time,
            'total_time': exec_time + transpile_time,
            'depth': circuit_transpiled.depth(),
            'gates': sum(circuit_transpiled.count_ops().values()),
            'gate_counts': dict(gate_counts),
            'shots': shots,
            'unique_outcomes': len(counts),
            'result': result
        }
        
    except Exception as e:
        print(f"✗ Execution failed: {e}")
        return {
            'success': False,
            'error': str(e)
        }


def print_summary(test_result, precision):
    """Print test summary"""
    print("\n" + "="*70)
    print("TEST SUMMARY")
    print("="*70)
    
    if not test_result['success']:
        print(f"❌ Test failed: {test_result['error']}")
        return
    
    print("✅ Test completed successfully")
    print()
    print(f"Circuit: 32-qubit QAOA from Classiq")
    print(f"Precision: {precision}")
    print(f"Shots: {test_result['shots']}")
    print()
    print("Performance:")
    print(f"  Transpile time: {test_result['transpile_time']:.3f}s")
    print(f"  Execution time: {test_result['exec_time']:.4f}s")
    print(f"  Total time: {test_result['total_time']:.4f}s")
    print(f"  Throughput: {test_result['shots'] / test_result['exec_time']:.2f} shots/sec")
    print()
    print("Circuit Statistics:")
    print(f"  Final depth: {test_result['depth']}")
    print(f"  Final gates: {test_result['gates']}")
    print(f"  Unique measurement outcomes: {test_result['unique_outcomes']}")
    print()
    print("="*70)


def main():
    """Main execution"""
    parser = argparse.ArgumentParser(
        description="QAOA Circuit Test - Single GPU",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Default parameters and settings
  python3 qaoa_test.py
  
  # Custom precision
  python3 qaoa_test.py --precision complex64
  
  # Custom shots
  python3 qaoa_test.py --shots 1024
  
  # Custom parameters (4 values required)
  python3 qaoa_test.py --params 0.5,0.3,0.6,0.4
  
  # Combination
  python3 qaoa_test.py --precision complex64 --shots 2048 --params 0.4,0.35,0.55,0.45
        """
    )
    
    parser.add_argument('--precision', type=str, default='complex128',
                        choices=['complex128', 'complex64'],
                        help='Precision: complex128 (default, 16 bytes) or complex64 (8 bytes)')
    
    parser.add_argument('--shots', type=int, default=100,
                        help='Number of measurement shots (default: 100)')
    
    parser.add_argument('--params', type=str, default='0.5,0.3,0.5,0.3',
                        help='Comma-separated parameter values (4 required, default: "0.5,0.3,0.5,0.3")')
    
    args = parser.parse_args()
    
    # Parse parameters
    try:
        param_values = [float(x.strip()) for x in args.params.split(',')]
        if len(param_values) != 4:
            print("Error: Exactly 4 parameter values required")
            return 1
    except ValueError:
        print("Error: Invalid parameter values. Must be comma-separated floats.")
        return 1
    
    # Show system info
    has_gpu = show_system_info(args.precision)
    
    if not has_gpu:
        print("\nCannot run test without GPU. Exiting.")
        return 1
    
    # Run test
    result = run_qaoa_test(param_values, args.shots, args.precision)
    
    # Print summary
    print_summary(result, args.precision)
    
    # Tips
    print("\n💡 Tips:")
    print("  - This 32-qubit circuit uses blocking (27-qubit chunks)")
    print("  - Try different parameter values to explore the solution space")
    print("  - Use --precision complex64 for faster execution")
    print("  - Higher shot counts give more accurate probability distributions")
    print()
    
    return 0 if result['success'] else 1


if __name__ == '__main__':
    sys.exit(main())
